### PR TITLE
Fix buildsystem to properly honor $(libdir) and other user variables

### PR DESCRIPTION
**Pull request by SoapGentoo**
AX_CREATE_PKGCONFIG_INFO is the recommended way to create .pc files
See: http://www.dwheeler.com/autotools/

### CODE REVIEW

**Comment by pullmoll** [comment]
Hmm, this is a lot of code for a change of how musl-fts.pc is generated.

Is the comment of @blueness 

> ...but your pull request to musl-fts will only make things harder for us.

valid? I would at least want to take some time to understand the PR and see if it works with our (Void Linux) build environment.

**Comment by blueness** [comment]
we need to rename musl-fts.pc to fts-standalone.pc.  so maybe i'm
overstanding the matter.  we can live with whatever changes will make
you're life easier.

On Fri, Jan 13, 2017 at 8:31 AM, Jürgen Buchmüller <notifications@github.com

**Comment by SoapGentoo** [comment]
@pullmoll Updated the PR, removed the macro, just replaced the variables. All variables that enter into the `.pc` file need to be user-configurable.

**Comment by pullmoll** [comment]
Thank you. Merged in v1.2.6

**Comment by SoapGentoo** [comment]
@pullmoll I don't see any of my changes in the code base. The .pc isn't installed, it still contains the old paths.

**Comment by pullmoll** [comment]
Hmm.. I fucked something up with pushing to the fork at voidlinux/musl-fts and not (also) my original repo.
Let me sort that out and probably do another version bump.

**Comment by pullmoll** [comment]
Now it's in `github.com/pullmoll/musl-fts`. Sorry for the confusion.

**Pull request closed without merging**
